apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
spec:
  minReadySeconds: 3
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx-test
  template:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx-testc
          image: registry.lab.lcarilla.de/website:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
